#!/usr/bin/env python3
"""
Script para construir el notebook refactorizado 01-intro-llm-agents.ipynb
con el template híbrido completo.
"""

import json
from datetime import datetime

def create_cell(cell_type, content, metadata=None):
    """Helper para crear una celda de notebook."""
    cell = {
        "cell_type": cell_type,
        "metadata": metadata or {},
        "source": content if isinstance(content, list) else [content]
    }

    if cell_type == "code":
        cell["execution_count"] = None
        cell["outputs"] = []

    return cell

def markdown_cell(content):
    """Crea una celda markdown."""
    return create_cell("markdown", content)

def code_cell(content):
    """Crea una celda de código."""
    return create_cell("code", content)

# Iniciar construcción del notebook
cells = []

# ========================================
# HEADER CON TOC COMPLETO
# ========================================
cells.append(markdown_cell([
    "# 01. Introducción a LLM Agents\n",
    "\n",
    "**Nivel:** 🟢 Principiante  \n",
    "**Tiempo estimado:** 90-120 minutos  \n",
    "**Prerequisitos:** Familiaridad básica con LLMs y APIs\n",
    "\n",
    "## 🎯 Objetivos de Aprendizaje\n",
    "\n",
    "Al finalizar este notebook, podrás:\n",
    "- Explicar la diferencia fundamental entre un LLM y un Agente basado en LLM\n",
    "- Identificar los componentes clave de un agente (percepción, razonamiento, acción)\n",
    "- Implementar un loop de agente simple desde cero\n",
    "- Comprender el ciclo observación → pensamiento → acción → observación\n",
    "- Configurar y usar APIs de LLMs (OpenAI, Anthropic, o modelos locales)\n",
    "- **Implementar 5 funciones core de sistemas agénticos (100 puntos)**\n",
    "\n",
    "---\n",
    "\n",
    "## 📋 Tabla de Contenidos\n",
    "\n",
    "1. [Motivación: ¿Por qué Agentes?](#1-motivacion)\n",
    "2. [Intuición Visual: Anatomía de un Agente](#2-intuicion-visual)\n",
    "3. [Fundamentos Matemáticos](#3-fundamentos-matematicos)\n",
    "4. [Implementación Desde Cero](#4-implementacion-desde-cero)\n",
    "5. [🎓 Ejercicios Prácticos Guiados (100 pts)](#5-ejercicios-graded)\n",
    "6. [Comparación de Frameworks](#6-frameworks)\n",
    "7. [Ejercicios Avanzados (Opcionales)](#7-ejercicios-avanzados)\n",
    "8. [📄 Papers y Referencias](#8-papers)\n",
    "9. [💡 Best Practices y Producción](#9-best-practices)\n",
    "10. [📍 Navegación y Próximos Pasos](#10-navegacion)\n",
    "\n",
    "---\n"
]))

# ========================================
# SECCIÓN 1: MOTIVACIÓN
# ========================================
cells.append(markdown_cell([
    '<a id="1-motivacion"></a>\n',
    "## 1. Motivación: ¿Por qué Agentes?\n",
    "\n",
    "### El Problema con LLMs Puros\n",
    "\n",
    "Imagina que le preguntas a ChatGPT: *\"¿Cuál es el clima en Madrid ahora mismo?\"*\n",
    "\n",
    "El LLM responderá algo como: *\"Lo siento, no tengo acceso a información en tiempo real...\"* \n",
    "\n",
    "**¿Por qué?** Porque un LLM puro:\n",
    "- Solo tiene conocimiento hasta su fecha de entrenamiento\n",
    "- No puede acceder a APIs o herramientas externas\n",
    "- No puede ejecutar acciones en el mundo real\n",
    "- Solo puede generar texto basado en su contexto\n",
    "\n",
    "### La Solución: Agentes\n",
    "\n",
    "Un **Agente basado en LLM** puede:\n",
    "1. **Razonar** sobre qué información necesita\n",
    "2. **Decidir** usar una herramienta (ej: API de clima)\n",
    "3. **Ejecutar** la acción (llamar a la API)\n",
    "4. **Observar** el resultado\n",
    "5. **Razonar nuevamente** con la nueva información\n",
    "6. **Responder** al usuario con datos actualizados\n",
    "\n",
    "### Pregunta Guía\n",
    "\n",
    "**Al final de este notebook responderemos:**\n",
    "*¿Cómo podemos transformar un LLM pasivo (solo genera texto) en un agente activo (razona y ejecuta acciones)?*\n"
]))

# ========================================
# SECCIÓN 2: INTUICIÓN VISUAL
# ========================================
cells.append(markdown_cell([
    '<a id="2-intuicion-visual"></a>\n',
    "## 2. Intuición Visual: Anatomía de un Agente\n",
    "\n",
    "### LLM vs Agente: Comparación\n",
    "\n",
    "```\n",
    "┌─────────────────────────────────────────────────────────────┐\n",
    "│                      LLM (Pasivo)                          │\n",
    "├─────────────────────────────────────────────────────────────┤\n",
    "│                                                             │\n",
    "│  Input (Prompt) ──────► [LLM] ──────► Output (Text)       │\n",
    "│                                                             │\n",
    "│  • Solo procesa texto                                      │\n",
    "│  • Una pasada, sin iteración                               │\n",
    "│  • No puede usar herramientas                              │\n",
    "│  • Conocimiento estático                                   │\n",
    "└─────────────────────────────────────────────────────────────┘\n",
    "\n",
    "┌─────────────────────────────────────────────────────────────┐\n",
    "│                    Agente (Activo)                         │\n",
    "├─────────────────────────────────────────────────────────────┤\n",
    "│                                                             │\n",
    "│           ┌──────────────────────────┐                     │\n",
    "│           │                          │                     │\n",
    "│           ▼                          │                     │\n",
    "│  Observación ──► Razonamiento ──► Acción                  │\n",
    "│      ▲         (LLM Core)        │                        │\n",
    "│      │                           │                        │\n",
    "│      │                           ▼                        │\n",
    "│      │                      [Herramientas]                │\n",
    "│      │                      • Web Search                  │\n",
    "│      │                      • Calculator                  │\n",
    "│      │                      • Database                    │\n",
    "│      │                      • Code Exec                   │\n",
    "│      └──────────────────────────┘                         │\n",
    "│                                                             │\n",
    "│  • Loop iterativo                                          │\n",
    "│  • Usa herramientas externas                               │\n",
    "│  • Actualiza conocimiento dinámicamente                    │\n",
    "│  • Toma decisiones y ejecuta acciones                      │\n",
    "└─────────────────────────────────────────────────────────────┘\n",
    "```\n",
    "\n",
    "### Componentes de un Agente\n",
    "\n",
    "1. **Cerebro (LLM)**: Razona sobre qué hacer\n",
    "2. **Memoria**: Recuerda interacciones pasadas y contexto\n",
    "3. **Herramientas**: Capacidades extendidas (APIs, calculadora, etc.)\n",
    "4. **Control Loop**: Orquesta el ciclo observar-pensar-actuar\n",
    "5. **Planner** (opcional): Descompone tareas complejas en pasos\n",
    "\n",
    "Visualizaremos esto con código a continuación.\n"
]))

# ========================================
# SETUP
# ========================================
cells.append(code_cell([
    "# Instalación de dependencias necesarias\n",
    "# Descomenta si no las tienes instaladas\n",
    "\n",
    "# !pip install openai anthropic python-dotenv plotly pandas\n",
    "# Para modelos locales (opcional):\n",
    "# !pip install transformers torch\n"
]))

cells.append(code_cell([
    "import os\n",
    "import json\n",
    "from typing import List, Dict, Optional, Callable\n",
    "from dataclasses import dataclass\n",
    "from datetime import datetime\n",
    "\n",
    "# Para visualizaciones\n",
    "import plotly.graph_objects as go\n",
    "from plotly.subplots import make_subplots\n",
    "\n",
    "# Para APIs de LLMs\n",
    "try:\n",
    "    from openai import OpenAI\n",
    "    OPENAI_AVAILABLE = True\n",
    "except ImportError:\n",
    "    OPENAI_AVAILABLE = False\n",
    "    print(\"⚠️  OpenAI no disponible. Instala con: pip install openai\")\n",
    "\n",
    "try:\n",
    "    from anthropic import Anthropic\n",
    "    ANTHROPIC_AVAILABLE = True\n",
    "except ImportError:\n",
    "    ANTHROPIC_AVAILABLE = False\n",
    "    print(\"⚠️  Anthropic no disponible. Instala con: pip install anthropic\")\n",
    "\n",
    "# Configuración\n",
    "from dotenv import load_dotenv\n",
    "load_dotenv()\n",
    "\n",
    "print(\"✅ Librerías importadas correctamente\")\n"
]))

# ========================================
# SECCIÓN 3: FUNDAMENTOS MATEMÁTICOS
# ========================================
cells.append(markdown_cell([
    '<a id="3-fundamentos-matematicos"></a>\n',
    "## 3. Fundamentos Matemáticos: Formalización del Agente\n",
    "\n",
    "### Definición Formal\n",
    "\n",
    "Un **agente** puede formalizarse como una función que mapea secuencias de percepciones a acciones:\n",
    "\n",
    "$$\n",
    "\\begin{align}\n",
    "\\pi: \\mathcal{O}^* &\\to \\mathcal{A} \\tag{1} \\\\\n",
    "\\text{donde: } & \\\\\n",
    "\\mathcal{O} &: \\text{espacio de observaciones} \\\\\n",
    "\\mathcal{A} &: \\text{espacio de acciones} \\\\\n",
    "\\pi &: \\text{política del agente (la \"estrategia\")} \\\\\n",
    "\\mathcal{O}^* &: \\text{historial de observaciones}\n",
    "\\end{align}\n",
    "$$\n",
    "\n",
    "### El Loop del Agente\n",
    "\n",
    "En cada paso temporal $t$:\n",
    "\n",
    "$$\n",
    "\\begin{align}\n",
    "o_t &= \\text{observe}(\\text{environment}) \\tag{2} \\\\\n",
    "s_t &= \\text{update\\_state}(s_{t-1}, o_t) \\tag{3} \\\\\n",
    "a_t &= \\pi(s_t) \\tag{4} \\\\\n",
    "\\text{environment} &= \\text{execute}(a_t) \\tag{5}\n",
    "\\end{align}\n",
    "$$\n",
    "\n",
    "Donde:\n",
    "- $o_t$: Observación en tiempo $t$\n",
    "- $s_t$: Estado interno del agente (memoria)\n",
    "- $a_t$: Acción elegida por la política\n",
    "- $\\pi$: Política implementada por el LLM\n",
    "\n",
    "### Para LLM Agents\n",
    "\n",
    "La política $\\pi$ es implementada por un LLM:\n",
    "\n",
    "$$\n",
    "\\begin{align}\n",
    "\\pi(s_t) &= \\text{LLM}(\\text{prompt}(s_t)) \\tag{6} \\\\\n",
    "\\text{prompt}(s_t) &= \\text{template}(\\text{system\\_msg}, \\text{history}_t, \\text{tools}) \\tag{7}\n",
    "\\end{align}\n",
    "$$\n",
    "\n",
    "**Key Insight:**\n",
    "> La \"inteligencia\" del agente emerge de cómo construimos el prompt que alimenta al LLM. El diseño del prompt determina qué tan bien razona y actúa el agente.\n",
    "\n",
    "### Ejemplo Numérico\n",
    "\n",
    "Supongamos:\n",
    "- Usuario pregunta: \"¿Cuánto es 15% de 340?\"\n",
    "- Agente tiene herramienta: `calculator`\n",
    "\n",
    "**Paso 1:** $o_0$ = \"¿Cuánto es 15% de 340?\"  \n",
    "**Paso 2:** LLM razona → decide usar `calculator(0.15 * 340)`  \n",
    "**Paso 3:** Herramienta ejecuta → $o_1$ = \"51.0\"  \n",
    "**Paso 4:** LLM genera respuesta final → \"El 15% de 340 es 51\"\n",
    "\n",
    "Este loop puede iterar múltiples veces según la complejidad de la tarea.\n"
]))

# ========================================
# SECCIÓN 4: IMPLEMENTACIÓN DESDE CERO
# ========================================
cells.append(markdown_cell([
    '<a id="4-implementacion-desde-cero"></a>\n',
    "## 4. Implementación Desde Cero: Simple Agent Loop\n",
    "\n",
    "Implementaremos un agente básico con tres componentes:\n",
    "1. **LLM Backend** (OpenAI, Anthropic, o simulado)\n",
    "2. **Herramientas simples** (calculadora, hora actual)\n",
    "3. **Loop de control**\n"
]))

cells.append(code_cell([
    "@dataclass\n",
    "class AgentAction:\n",
    "    \"\"\"Representa una acción del agente\"\"\"\n",
    "    tool: str  # Nombre de la herramienta a usar\n",
    "    tool_input: str  # Input para la herramienta\n",
    "    reasoning: str  # Razonamiento del agente\n",
    "\n",
    "@dataclass\n",
    "class Observation:\n",
    "    \"\"\"Representa una observación del entorno\"\"\"\n",
    "    content: str  # Contenido de la observación\n",
    "    timestamp: datetime  # Cuándo ocurrió\n",
    "\n",
    "class SimpleTool:\n",
    "    \"\"\"Clase base para herramientas del agente\"\"\"\n",
    "    def __init__(self, name: str, description: str, func: Callable):\n",
    "        self.name = name\n",
    "        self.description = description\n",
    "        self.func = func\n",
    "    \n",
    "    def run(self, input_str: str) -> str:\n",
    "        \"\"\"Ejecuta la herramienta con el input dado\"\"\"\n",
    "        try:\n",
    "            result = self.func(input_str)\n",
    "            return str(result)\n",
    "        except Exception as e:\n",
    "            return f\"Error: {str(e)}\"\n",
    "\n",
    "# Definir herramientas simples\n",
    "def calculator(expression: str) -> float:\n",
    "    \"\"\"Calcula expresiones matemáticas simples\"\"\"\n",
    "    # ADVERTENCIA: eval es peligroso en producción, usar solo para demos\n",
    "    # En producción, usa un parser matemático seguro\n",
    "    return eval(expression)\n",
    "\n",
    "def get_current_time(timezone: str = \"UTC\") -> str:\n",
    "    \"\"\"Retorna la hora actual\"\"\"\n",
    "    return datetime.now().strftime(\"%Y-%m-%d %H:%M:%S\")\n",
    "\n",
    "# Crear herramientas\n",
    "calculator_tool = SimpleTool(\n",
    "    name=\"calculator\",\n",
    "    description=\"Útil para hacer cálculos matemáticos. Input: expresión matemática en Python.\",\n",
    "    func=calculator\n",
    ")\n",
    "\n",
    "time_tool = SimpleTool(\n",
    "    name=\"get_time\",\n",
    "    description=\"Retorna la fecha y hora actual.\",\n",
    "    func=get_current_time\n",
    ")\n",
    "\n",
    "print(\"✅ Herramientas creadas:\", [calculator_tool.name, time_tool.name])\n"
]))

# Clase SimpleAgent (larga)
cells.append(code_cell([
    "class SimpleAgent:\n",
    "    \"\"\"\n",
    "    Implementación básica de un agente LLM.\n",
    "    \n",
    "    El agente:\n",
    "    1. Recibe una query del usuario\n",
    "    2. Decide si necesita usar una herramienta\n",
    "    3. Ejecuta la herramienta si es necesario\n",
    "    4. Genera una respuesta final\n",
    "    \"\"\"\n",
    "    \n",
    "    def __init__(self, tools: List[SimpleTool], llm_backend: str = \"simulated\"):\n",
    "        \"\"\"\n",
    "        Args:\n",
    "            tools: Lista de herramientas disponibles\n",
    "            llm_backend: \"openai\", \"anthropic\", o \"simulated\"\n",
    "        \"\"\"\n",
    "        self.tools = {tool.name: tool for tool in tools}\n",
    "        self.llm_backend = llm_backend\n",
    "        self.history: List[Dict] = []  # Historial de interacciones\n",
    "        \n",
    "        # Configurar cliente LLM\n",
    "        if llm_backend == \"openai\" and OPENAI_AVAILABLE:\n",
    "            self.client = OpenAI(api_key=os.getenv(\"OPENAI_API_KEY\"))\n",
    "            self.model = \"gpt-4-turbo-preview\"\n",
    "        elif llm_backend == \"anthropic\" and ANTHROPIC_AVAILABLE:\n",
    "            self.client = Anthropic(api_key=os.getenv(\"ANTHROPIC_API_KEY\"))\n",
    "            self.model = \"claude-3-opus-20240229\"\n",
    "        else:\n",
    "            self.client = None\n",
    "            print(\"⚠️  Usando LLM simulado para demostración\")\n",
    "    \n",
    "    def _build_prompt(self, query: str) -> str:\n",
    "        \"\"\"Construye el prompt para el LLM\"\"\"\n",
    "        tools_desc = \"\\n\".join([\n",
    "            f\"- {name}: {tool.description}\" \n",
    "            for name, tool in self.tools.items()\n",
    "        ])\n",
    "        \n",
    "        prompt = f\"\"\"Eres un asistente útil que puede usar herramientas para responder preguntas.\n",
    "\n",
    "Herramientas disponibles:\n",
    "{tools_desc}\n",
    "\n",
    "Para usar una herramienta, responde EXACTAMENTE en este formato:\n",
    "RAZONAMIENTO: [tu razonamiento]\n",
    "HERRAMIENTA: [nombre_herramienta]\n",
    "INPUT: [input para la herramienta]\n",
    "\n",
    "Si no necesitas una herramienta, responde directamente.\n",
    "\n",
    "Pregunta del usuario: {query}\n",
    "\n",
    "Tu respuesta:\"\"\"\n",
    "        return prompt\n",
    "    \n",
    "    def _call_llm(self, prompt: str) -> str:\n",
    "        \"\"\"Llama al LLM y retorna la respuesta\"\"\"\n",
    "        if self.llm_backend == \"openai\" and self.client:\n",
    "            response = self.client.chat.completions.create(\n",
    "                model=self.model,\n",
    "                messages=[{\"role\": \"user\", \"content\": prompt}],\n",
    "                temperature=0.0\n",
    "            )\n",
    "            return response.choices[0].message.content\n",
    "        \n",
    "        elif self.llm_backend == \"anthropic\" and self.client:\n",
    "            response = self.client.messages.create(\n",
    "                model=self.model,\n",
    "                max_tokens=1024,\n",
    "                messages=[{\"role\": \"user\", \"content\": prompt}]\n",
    "            )\n",
    "            return response.content[0].text\n",
    "        \n",
    "        else:\n",
    "            # LLM simulado para demostración\n",
    "            return self._simulated_llm(prompt)\n",
    "    \n",
    "    def _simulated_llm(self, prompt: str) -> str:\n",
    "        \"\"\"Simula un LLM con reglas básicas (solo para demo)\"\"\"\n",
    "        query_lower = prompt.lower()\n",
    "        \n",
    "        # Detectar si necesita calculadora\n",
    "        if any(word in query_lower for word in ['calcular', 'cuánto es', '+', '-', '*', '/', '%']):\n",
    "            # Intentar extraer expresión matemática\n",
    "            import re\n",
    "            # Buscar patrones como \"15% de 340\" o \"2 + 2\"\n",
    "            match = re.search(r'(\\d+)%\\s+de\\s+(\\d+)', query_lower)\n",
    "            if match:\n",
    "                expr = f\"{match.group(1)} * {match.group(2)} / 100\"\n",
    "            else:\n",
    "                # Buscar expresiones matemáticas simples\n",
    "                expr_match = re.search(r'[\\d+\\-*/().\\s]+', query_lower)\n",
    "                expr = expr_match.group(0) if expr_match else \"1+1\"\n",
    "            \n",
    "            return f\"\"\"RAZONAMIENTO: Necesito calcular una expresión matemática\n",
    "HERRAMIENTA: calculator\n",
    "INPUT: {expr}\"\"\"\n",
    "        \n",
    "        # Detectar si pregunta por hora\n",
    "        elif any(word in query_lower for word in ['hora', 'fecha', 'tiempo']):\n",
    "            return \"\"\"RAZONAMIENTO: Usuario pregunta por la hora actual\n",
    "HERRAMIENTA: get_time\n",
    "INPUT: UTC\"\"\"\n",
    "        \n",
    "        # Respuesta directa\n",
    "        return \"Hola, puedo ayudarte con cálculos y consultar la hora.\"\n",
    "    \n",
    "    def _parse_action(self, llm_response: str) -> Optional[AgentAction]:\n",
    "        \"\"\"Parsea la respuesta del LLM para extraer una acción\"\"\"\n",
    "        if \"HERRAMIENTA:\" not in llm_response:\n",
    "            return None\n",
    "        \n",
    "        lines = llm_response.strip().split('\\n')\n",
    "        action_dict = {}\n",
    "        \n",
    "        for line in lines:\n",
    "            if line.startswith(\"RAZONAMIENTO:\"):\n",
    "                action_dict['reasoning'] = line.replace(\"RAZONAMIENTO:\", \"\").strip()\n",
    "            elif line.startswith(\"HERRAMIENTA:\"):\n",
    "                action_dict['tool'] = line.replace(\"HERRAMIENTA:\", \"\").strip()\n",
    "            elif line.startswith(\"INPUT:\"):\n",
    "                action_dict['tool_input'] = line.replace(\"INPUT:\", \"\").strip()\n",
    "        \n",
    "        if 'tool' in action_dict:\n",
    "            return AgentAction(\n",
    "                tool=action_dict.get('tool', ''),\n",
    "                tool_input=action_dict.get('tool_input', ''),\n",
    "                reasoning=action_dict.get('reasoning', '')\n",
    "            )\n",
    "        return None\n",
    "    \n",
    "    def run(self, query: str, max_iterations: int = 3, verbose: bool = True) -> str:\n",
    "        \"\"\"\n",
    "        Ejecuta el loop del agente.\n",
    "        \n",
    "        Args:\n",
    "            query: Pregunta del usuario\n",
    "            max_iterations: Máximo número de iteraciones del loop\n",
    "            verbose: Si True, imprime pasos intermedios\n",
    "        \n",
    "        Returns:\n",
    "            Respuesta final del agente\n",
    "        \"\"\"\n",
    "        if verbose:\n",
    "            print(f\"\\n{'='*60}\")\n",
    "            print(f\"🤖 AGENTE EJECUTÁNDOSE\")\n",
    "            print(f\"{'='*60}\")\n",
    "            print(f\"\\n📝 Query: {query}\\n\")\n",
    "        \n",
    "        for iteration in range(max_iterations):\n",
    "            if verbose:\n",
    "                print(f\"\\n--- Iteración {iteration + 1} ---\")\n",
    "            \n",
    "            # 1. Construir prompt y llamar LLM\n",
    "            prompt = self._build_prompt(query)\n",
    "            llm_response = self._call_llm(prompt)\n",
    "            \n",
    "            if verbose:\n",
    "                print(f\"\\n💭 LLM Response:\\n{llm_response}\")\n",
    "            \n",
    "            # 2. Parsear acción\n",
    "            action = self._parse_action(llm_response)\n",
    "            \n",
    "            # 3. Si no hay acción, retornar respuesta\n",
    "            if action is None:\n",
    "                if verbose:\n",
    "                    print(f\"\\n✅ Respuesta final (sin herramientas)\")\n",
    "                return llm_response\n",
    "            \n",
    "            # 4. Ejecutar herramienta\n",
    "            if action.tool not in self.tools:\n",
    "                error_msg = f\"Error: Herramienta '{action.tool}' no disponible\"\n",
    "                if verbose:\n",
    "                    print(f\"\\n❌ {error_msg}\")\n",
    "                return error_msg\n",
    "            \n",
    "            if verbose:\n",
    "                print(f\"\\n🔧 Usando herramienta: {action.tool}\")\n",
    "                print(f\"📥 Input: {action.tool_input}\")\n",
    "            \n",
    "            observation = self.tools[action.tool].run(action.tool_input)\n",
    "            \n",
    "            if verbose:\n",
    "                print(f\"📤 Output: {observation}\")\n",
    "            \n",
    "            # 5. Actualizar query con observación\n",
    "            query = f\"\"\"Pregunta original: {query}\n",
    "Razonamiento: {action.reasoning}\n",
    "Herramienta usada: {action.tool}\n",
    "Resultado: {observation}\n",
    "\n",
    "Por favor, proporciona la respuesta final al usuario basándote en esta información.\"\"\"\n",
    "        \n",
    "        # Si llegamos al máximo de iteraciones\n",
    "        final_prompt = self._build_prompt(query)\n",
    "        final_response = self._call_llm(final_prompt)\n",
    "        \n",
    "        if verbose:\n",
    "            print(f\"\\n✅ Respuesta final:\\n{final_response}\")\n",
    "        \n",
    "        return final_response\n",
    "\n",
    "print(\"✅ Clase SimpleAgent implementada\")\n"
]))

# Demos
cells.append(markdown_cell(["### Probemos nuestro agente\n"]))

cells.append(code_cell([
    "# Crear agente con herramientas\n",
    "agent = SimpleAgent(\n",
    "    tools=[calculator_tool, time_tool],\n",
    "    llm_backend=\"simulated\"  # Cambiar a \"openai\" o \"anthropic\" si tienes API keys\n",
    ")\n",
    "\n",
    "# Probar con una pregunta matemática\n",
    "result1 = agent.run(\"¿Cuánto es el 15% de 340?\")\n",
    "print(f\"\\n{'='*60}\")\n",
    "print(f\"Resultado Final: {result1}\")\n"
]))

cells.append(code_cell([
    "# Probar con pregunta de tiempo\n",
    "result2 = agent.run(\"¿Qué hora es?\")\n",
    "print(f\"\\n{'='*60}\")\n",
    "print(f\"Resultado Final: {result2}\")\n"
]))

print("Construyendo secciones 1-4... OK")

# ========================================
# SECCIÓN 5: EJERCICIOS GRADED
# ========================================
print("Construyendo sección 5: Ejercicios GRADED...")

cells.append(markdown_cell([
    '<a id="5-ejercicios-graded"></a>\n',
    "## 5. 🎓 Ejercicios Prácticos Guiados (100 pts)\n",
    "\n",
    "En esta sección implementarás las funciones core de un sistema agéntico desde cero. Cada ejercicio construye sobre el anterior, llevándote desde parsear respuestas básicas hasta implementar un agente completo con memoria.\n",
    "\n",
    "### 📊 Sistema de Calificación\n",
    "\n",
    "- **Total de puntos**: 100\n",
    "- **Mínimo para aprobar**: 70\n",
    "- **Ejercicios**:\n",
    "  1. `parse_tool_response` (15 pts) - Parsear respuestas del LLM\n",
    "  2. `execute_tool` (15 pts) - Ejecutar herramientas de forma segura\n",
    "  3. `build_agent_prompt` (20 pts) - Construir prompts efectivos\n",
    "  4. `simple_agent_step` (25 pts) - Implementar un paso del loop agéntico\n",
    "  5. `agent_with_memory` (25 pts) - Agente con memoria conversacional\n",
    "\n",
    "### 🧪 Cómo Usar el Autograder\n",
    "\n",
    "```python\n",
    "# 1. Implementa tu función donde dice GRADED FUNCTION\n",
    "# 2. Corre la celda de código\n",
    "# 3. Ejecuta el grader:\n",
    "from tests.test_01_llm_agents import LLMAgentsGrader\n",
    "grader = LLMAgentsGrader()\n",
    "grader.test_parse_tool_response(parse_tool_response)\n",
    "```\n",
    "\n",
    "### 💡 Tips\n",
    "\n",
    "- Lee cuidadosamente los docstrings y ejemplos\n",
    "- Los tests verifican casos edge (inputs vacíos, formatos incorrectos, etc.)\n",
    "- Puedes correr tests individuales o todos a la vez\n",
    "- Si fallas un test, el mensaje de error te dará pistas\n",
    "\n",
    "---\n"
]))

# Importar autograder
cells.append(code_cell([
    "# Importar el sistema de autograding\n",
    "import sys\n",
    "sys.path.append('/home/user/TUTORIALS-AI-AGENTS/rutas/03-llm-agents')\n",
    "\n",
    "from tests.test_01_llm_agents import LLMAgentsGrader\n",
    "\n",
    "# Crear instancia del grader\n",
    "grader = LLMAgentsGrader()\n",
    "\n",
    "print(f\"✅ Autograder cargado\")\n",
    "print(f\"📊 Total de puntos disponibles: {grader.total_points}\")\n",
    "print(f\"🎯 Mínimo para aprobar: {grader.passing_grade}\")\n",
    "print(f\"\\n📝 Ejercicios:\")\n",
    "for name, points in grader.exercise_points.items():\n",
    "    print(f\"  - {name}: {points} pts\")\n"
]))

# EJERCICIO 1
cells.append(markdown_cell([
    "### Ejercicio 1: Parsear Respuestas del LLM (15 pts)\n",
    "\n",
    "**Objetivo**: Implementar una función que parsee la respuesta del LLM para extraer llamadas a herramientas.\n",
    "\n",
    "**Contexto**: Los agentes reciben respuestas del LLM en un formato específico. Necesitamos parsear estas respuestas para identificar si el LLM quiere usar una herramienta.\n",
    "\n",
    "**Formato esperado**:\n",
    "```\n",
    "PENSAMIENTO: [razonamiento del agente]\n",
    "HERRAMIENTA: [nombre de la herramienta]\n",
    "INPUT: [input para la herramienta]\n",
    "```\n",
    "\n",
    "**Tu tarea**: Implementar `parse_tool_response` que:\n",
    "- Detecte si hay una llamada a herramienta (buscar \"HERRAMIENTA:\")\n",
    "- Extraiga el nombre de la herramienta, input, y pensamiento\n",
    "- Retorne un diccionario con estos campos\n",
    "- Retorne `None` si no hay llamada a herramienta\n",
    "\n",
    "**Tests verifican**:\n",
    "1. Parseo básico de formato correcto\n",
    "2. Retorna `None` cuando no hay herramienta\n",
    "3. Maneja inputs multilinea\n",
    "4. Funciona sin campo PENSAMIENTO (opcional)\n",
    "5. Es case-insensitive\n"
]))

cells.append(code_cell([
    "# GRADED FUNCTION: parse_tool_response\n",
    "\n",
    "def parse_tool_response(llm_response: str) -> Optional[Dict[str, str]]:\n",
    "    \"\"\"\n",
    "    Parsea la respuesta del LLM para extraer llamadas a herramientas.\n",
    "    \n",
    "    El formato esperado es:\n",
    "    PENSAMIENTO: <razonamiento>\n",
    "    HERRAMIENTA: <nombre_herramienta>\n",
    "    INPUT: <input_para_herramienta>\n",
    "    \n",
    "    Args:\n",
    "        llm_response: Respuesta completa del LLM\n",
    "    \n",
    "    Returns:\n",
    "        Dict con keys 'tool_name', 'tool_input', 'reasoning' si hay llamada a herramienta\n",
    "        None si no hay llamada a herramienta\n",
    "    \n",
    "    Ejemplos:\n",
    "        >>> response = \"\"\"PENSAMIENTO: Necesito calcular\n",
    "        ... HERRAMIENTA: calculator\n",
    "        ... INPUT: 2 + 2\"\"\"\n",
    "        >>> parse_tool_response(response)\n",
    "        {'tool_name': 'calculator', 'tool_input': '2 + 2', 'reasoning': 'Necesito calcular'}\n",
    "        \n",
    "        >>> parse_tool_response(\"No necesito herramientas\")\n",
    "        None\n",
    "    \"\"\"\n",
    "    # TODO: Implementa esta función\n",
    "    # Pistas:\n",
    "    # 1. Verifica si \"HERRAMIENTA:\" está en la respuesta (case-insensitive)\n",
    "    # 2. Divide la respuesta en líneas\n",
    "    # 3. Para cada línea, busca PENSAMIENTO:, HERRAMIENTA:, INPUT:\n",
    "    # 4. Extrae el texto después de los dos puntos\n",
    "    # 5. Retorna dict o None según corresponda\n",
    "    \n",
    "    pass\n",
    "\n",
    "# Descomenta para probar tu función manualmente:\n",
    "# test_response = \"\"\"PENSAMIENTO: Necesito calcular\n",
    "# HERRAMIENTA: calculator\n",
    "# INPUT: 2 + 2\"\"\"\n",
    "# print(parse_tool_response(test_response))\n"
]))

cells.append(code_cell([
    "# Correr tests para Ejercicio 1\n",
    "# Descomenta cuando hayas implementado la función:\n",
    "\n",
    "# grader.test_parse_tool_response(parse_tool_response)\n"
]))

# EJERCICIO 2
cells.append(markdown_cell([
    "### Ejercicio 2: Ejecutar Herramientas de Forma Segura (15 pts)\n",
    "\n",
    "**Objetivo**: Implementar una función que ejecute herramientas de forma segura, manejando errores.\n",
    "\n",
    "**Contexto**: Las herramientas pueden fallar (división por cero, API caída, etc.). Necesitamos manejar estos errores gracefully.\n",
    "\n",
    "**Tu tarea**: Implementar `execute_tool` que:\n",
    "- Tome un diccionario de herramientas disponibles\n",
    "- Verifique que la herramienta existe\n",
    "- Ejecute la herramienta con el input dado\n",
    "- Maneje errores y retorne mensajes informativos\n",
    "- Retorne el resultado como string\n",
    "\n",
    "**Tests verifican**:\n",
    "1. Ejecución exitosa de herramienta válida\n",
    "2. Manejo de herramientas inexistentes\n",
    "3. Manejo de errores durante ejecución\n",
    "4. Conversión correcta a string del resultado\n"
]))

cells.append(code_cell([
    "# GRADED FUNCTION: execute_tool\n",
    "\n",
    "def execute_tool(tool_name: str, tool_input: str, available_tools: Dict[str, SimpleTool]) -> str:\n",
    "    \"\"\"\n",
    "    Ejecuta una herramienta de forma segura.\n",
    "    \n",
    "    Args:\n",
    "        tool_name: Nombre de la herramienta a ejecutar\n",
    "        tool_input: Input para la herramienta\n",
    "        available_tools: Diccionario {nombre: SimpleTool}\n",
    "    \n",
    "    Returns:\n",
    "        Resultado de la herramienta como string, o mensaje de error\n",
    "    \n",
    "    Ejemplos:\n",
    "        >>> tools = {'calculator': SimpleTool('calculator', 'calc', lambda x: eval(x))}\n",
    "        >>> execute_tool('calculator', '2+2', tools)\n",
    "        '4'\n",
    "        \n",
    "        >>> execute_tool('nonexistent', 'foo', tools)\n",
    "        \"Error: Herramienta 'nonexistent' no está disponible\"\n",
    "    \"\"\"\n",
    "    # TODO: Implementa esta función\n",
    "    # Pistas:\n",
    "    # 1. Verifica si tool_name está en available_tools\n",
    "    # 2. Si no está, retorna mensaje de error con el nombre de la herramienta\n",
    "    # 3. Si está, ejecuta tool.run(tool_input) dentro de try/except\n",
    "    # 4. Convierte el resultado a string\n",
    "    # 5. Si hay excepción, retorna mensaje de error\n",
    "    \n",
    "    pass\n",
    "\n",
    "# Descomenta para probar:\n",
    "# tools_test = {'calculator': calculator_tool}\n",
    "# print(execute_tool('calculator', '10 * 5', tools_test))\n"
]))

cells.append(code_cell([
    "# Correr tests para Ejercicio 2\n",
    "# Descomenta cuando hayas implementado la función:\n",
    "\n",
    "# grader.test_execute_tool(execute_tool)\n"
]))

# EJERCICIO 3
cells.append(markdown_cell([
    "### Ejercicio 3: Construir Prompts Efectivos (20 pts)\n",
    "\n",
    "**Objetivo**: Implementar una función que construya prompts efectivos para el agente.\n",
    "\n",
    "**Contexto**: El prompt es crítico para el desempeño del agente. Debe incluir:\n",
    "- Descripción clara de herramientas disponibles\n",
    "- Formato esperado para respuestas\n",
    "- La query del usuario\n",
    "- Opcionalmente, historial de conversación\n",
    "\n",
    "**Tu tarea**: Implementar `build_agent_prompt` que:\n",
    "- Liste las herramientas disponibles con sus descripciones\n",
    "- Especifique el formato de respuesta esperado\n",
    "- Incluya la query del usuario\n",
    "- Opcionalmente incluya historial previo\n",
    "\n",
    "**Tests verifican**:\n",
    "1. Prompt incluye todas las herramientas\n",
    "2. Prompt incluye la query del usuario\n",
    "3. Prompt incluye instrucciones de formato\n",
    "4. Maneja historial correctamente (opcional)\n"
]))

cells.append(code_cell([
    "# GRADED FUNCTION: build_agent_prompt\n",
    "\n",
    "def build_agent_prompt(\n",
    "    query: str,\n",
    "    available_tools: Dict[str, SimpleTool],\n",
    "    history: Optional[List[Dict]] = None\n",
    ") -> str:\n",
    "    \"\"\"\n",
    "    Construye el prompt para el agente LLM.\n",
    "    \n",
    "    Args:\n",
    "        query: Pregunta del usuario\n",
    "        available_tools: Diccionario de herramientas disponibles\n",
    "        history: Lista opcional de interacciones previas [{\"role\": \"user\", \"content\": ...}, ...]\n",
    "    \n",
    "    Returns:\n",
    "        Prompt completo como string\n",
    "    \n",
    "    El prompt debe seguir esta estructura:\n",
    "    1. System message explicando el rol del agente\n",
    "    2. Lista de herramientas disponibles con sus descripciones\n",
    "    3. Instrucciones de formato (PENSAMIENTO/HERRAMIENTA/INPUT)\n",
    "    4. Historial previo (si existe)\n",
    "    5. Query actual del usuario\n",
    "    \"\"\"\n",
    "    # TODO: Implementa esta función\n",
    "    # Pistas:\n",
    "    # 1. Comienza con un system message claro\n",
    "    # 2. Lista las herramientas: \"- {nombre}: {descripción}\"\n",
    "    # 3. Explica el formato de respuesta esperado\n",
    "    # 4. Si hay historial, inclúyelo antes de la query actual\n",
    "    # 5. Termina con la query del usuario\n",
    "    \n",
    "    pass\n",
    "\n",
    "# Descomenta para probar:\n",
    "# tools_test = {'calculator': calculator_tool, 'time': time_tool}\n",
    "# prompt = build_agent_prompt(\"¿Qué hora es?\", tools_test)\n",
    "# print(prompt)\n"
]))

cells.append(code_cell([
    "# Correr tests para Ejercicio 3\n",
    "# Descomenta cuando hayas implementado la función:\n",
    "\n",
    "# grader.test_build_agent_prompt(build_agent_prompt)\n"
]))

# EJERCICIO 4
cells.append(markdown_cell([
    "### Ejercicio 4: Implementar un Paso del Loop Agéntico (25 pts)\n",
    "\n",
    "**Objetivo**: Implementar una iteración completa del loop: prompt → LLM → parse → execute → resultado.\n",
    "\n",
    "**Contexto**: Este es el corazón del agente. En cada paso:\n",
    "1. Construimos el prompt\n",
    "2. Llamamos al LLM\n",
    "3. Parseamos la respuesta\n",
    "4. Si hay tool call, ejecutamos la herramienta\n",
    "5. Retornamos el resultado\n",
    "\n",
    "**Tu tarea**: Implementar `simple_agent_step` que orqueste un paso completo.\n",
    "\n",
    "**Tests verifican**:\n",
    "1. Retorna respuesta directa si no hay tool call\n",
    "2. Ejecuta herramienta si hay tool call\n",
    "3. Maneja herramientas inexistentes\n",
    "4. Retorna resultado correcto\n"
]))

cells.append(code_cell([
    "# GRADED FUNCTION: simple_agent_step\n",
    "\n",
    "def simple_agent_step(\n",
    "    query: str,\n",
    "    available_tools: Dict[str, SimpleTool],\n",
    "    llm_function: Callable[[str], str]\n",
    ") -> Dict[str, any]:\n",
    "    \"\"\"\n",
    "    Ejecuta un paso del loop agéntico.\n",
    "    \n",
    "    Args:\n",
    "        query: Query del usuario\n",
    "        available_tools: Herramientas disponibles\n",
    "        llm_function: Función que toma un prompt y retorna respuesta del LLM\n",
    "    \n",
    "    Returns:\n",
    "        Diccionario con:\n",
    "        - 'response': Respuesta final (string)\n",
    "        - 'used_tool': Nombre de herramienta usada o None\n",
    "        - 'tool_result': Resultado de la herramienta o None\n",
    "    \n",
    "    Ejemplo:\n",
    "        >>> def mock_llm(prompt):\n",
    "        ...     return \"HERRAMIENTA: calculator\\nINPUT: 2+2\"\n",
    "        >>> tools = {'calculator': SimpleTool('calc', 'desc', lambda x: eval(x))}\n",
    "        >>> result = simple_agent_step(\"Calcula 2+2\", tools, mock_llm)\n",
    "        >>> result['tool_result']\n",
    "        '4'\n",
    "    \"\"\"\n",
    "    # TODO: Implementa esta función\n",
    "    # Pistas:\n",
    "    # 1. Usa build_agent_prompt para construir el prompt\n",
    "    # 2. Llama a llm_function con el prompt\n",
    "    # 3. Usa parse_tool_response para parsear la respuesta\n",
    "    # 4. Si no hay tool call, retorna la respuesta del LLM directamente\n",
    "    # 5. Si hay tool call, usa execute_tool para ejecutarla\n",
    "    # 6. Retorna diccionario con todos los campos requeridos\n",
    "    \n",
    "    pass\n",
    "\n",
    "# Descomenta para probar:\n",
    "# def mock_llm(prompt):\n",
    "#     return \"\"\"PENSAMIENTO: Necesito calcular\n",
    "# HERRAMIENTA: calculator\n",
    "# INPUT: 15 * 340 / 100\"\"\"\n",
    "# \n",
    "# tools_test = {'calculator': calculator_tool}\n",
    "# result = simple_agent_step(\"¿Cuánto es 15% de 340?\", tools_test, mock_llm)\n",
    "# print(result)\n"
]))

cells.append(code_cell([
    "# Correr tests para Ejercicio 4\n",
    "# Descomenta cuando hayas implementado la función:\n",
    "\n",
    "# grader.test_simple_agent_step(simple_agent_step)\n"
]))

# EJERCICIO 5
cells.append(markdown_cell([
    "### Ejercicio 5: Agente con Memoria Conversacional (25 pts)\n",
    "\n",
    "**Objetivo**: Implementar un agente que mantenga memoria de interacciones previas.\n",
    "\n",
    "**Contexto**: Los agentes útiles recuerdan el contexto de la conversación. Esto permite:\n",
    "- Referencias anafóricas (\"ahora multiplica ese resultado por 2\")\n",
    "- Continuidad en la conversación\n",
    "- Mejores respuestas contextualizadas\n",
    "\n",
    "**Tu tarea**: Implementar `agent_with_memory` que:\n",
    "- Mantenga un historial de queries y respuestas\n",
    "- Incluya el historial en el prompt\n",
    "- Permita múltiples turnos de conversación\n",
    "- Retorne respuesta y historial actualizado\n",
    "\n",
    "**Tests verifican**:\n",
    "1. Primera query sin historial funciona\n",
    "2. Segunda query incluye historial previo\n",
    "3. Historial se actualiza correctamente\n",
    "4. Contexto se mantiene a través de múltiples turnos\n"
]))

cells.append(code_cell([
    "# GRADED FUNCTION: agent_with_memory\n",
    "\n",
    "def agent_with_memory(\n",
    "    query: str,\n",
    "    available_tools: Dict[str, SimpleTool],\n",
    "    llm_function: Callable[[str], str],\n",
    "    conversation_history: Optional[List[Dict]] = None\n",
    ") -> Dict[str, any]:\n",
    "    \"\"\"\n",
    "    Ejecuta un paso del agente manteniendo memoria conversacional.\n",
    "    \n",
    "    Args:\n",
    "        query: Query actual del usuario\n",
    "        available_tools: Herramientas disponibles\n",
    "        llm_function: Función LLM\n",
    "        conversation_history: Historial previo (lista de dicts con 'role' y 'content')\n",
    "    \n",
    "    Returns:\n",
    "        Diccionario con:\n",
    "        - 'response': Respuesta del agente\n",
    "        - 'updated_history': Historial actualizado con esta interacción\n",
    "        - 'used_tool': Herramienta usada o None\n",
    "    \n",
    "    Ejemplo:\n",
    "        >>> history = []\n",
    "        >>> result1 = agent_with_memory(\"Calcula 10*5\", tools, llm, history)\n",
    "        >>> result2 = agent_with_memory(\"Suma 20\", tools, llm, result1['updated_history'])\n",
    "        # result2 debería usar el contexto de que el resultado anterior fue 50\n",
    "    \"\"\"\n",
    "    # TODO: Implementa esta función\n",
    "    # Pistas:\n",
    "    # 1. Inicializa conversation_history como lista vacía si es None\n",
    "    # 2. Usa build_agent_prompt con history incluido\n",
    "    # 3. Ejecuta el paso del agente (similar a simple_agent_step)\n",
    "    # 4. Agrega la query actual al historial: {'role': 'user', 'content': query}\n",
    "    # 5. Agrega la respuesta al historial: {'role': 'assistant', 'content': response}\n",
    "    # 6. Retorna response, updated_history, y used_tool\n",
    "    \n",
    "    pass\n",
    "\n",
    "# Descomenta para probar:\n",
    "# history = []\n",
    "# result1 = agent_with_memory(\"Calcula 10 * 5\", {'calculator': calculator_tool}, mock_llm, history)\n",
    "# print(\"Primera respuesta:\", result1['response'])\n",
    "# print(\"Historial:\", result1['updated_history'])\n"
]))

cells.append(code_cell([
    "# Correr tests para Ejercicio 5\n",
    "# Descomenta cuando hayas implementado la función:\n",
    "\n",
    "# grader.test_agent_with_memory(agent_with_memory)\n"
]))

# Calificación final
cells.append(markdown_cell([
    "### 📊 Calificación Final\n",
    "\n",
    "Ejecuta esta celda para obtener tu calificación completa:\n"
]))

cells.append(code_cell([
    "# Descomenta para obtener tu calificación completa:\n",
    "\n",
    "# grader.grade_all({\n",
    "#     'parse_tool_response': parse_tool_response,\n",
    "#     'execute_tool': execute_tool,\n",
    "#     'build_agent_prompt': build_agent_prompt,\n",
    "#     'simple_agent_step': simple_agent_step,\n",
    "#     'agent_with_memory': agent_with_memory\n",
    "# })\n"
]))

print("Sección 5: Ejercicios GRADED... OK")

# Continuará con secciones 6-10...
print("\\nNotebook generado parcialmente. Continuando con secciones 6-10...")

# ========================================
# SECCIÓN 6: FRAMEWORKS (EXPANDIDA)
# ========================================
print("Construyendo sección 6: Frameworks...")

cells.append(markdown_cell([
    '<a id="6-frameworks"></a>\n',
    "## 6. Comparación de Frameworks para Agentes\n",
    "\n",
    "Ahora que entiendes cómo funcionan los agentes internamente, veamos los frameworks populares que abstraen esta complejidad.\n",
    "\n",
    "### Frameworks Principales\n",
    "\n",
    "| Framework | Especialidad | Pros | Contras | Mejor Para |\n",
    "|-----------|-------------|------|---------|------------|\n",
    "| **LangChain** | General purpose | Ecosistema rico, documentación | Complejidad, abstracciones pesadas | Prototipado rápido |\n",
    "| **LlamaIndex** | RAG + Data | Excelente para datos estructurados | Menos flexible para agentes generales | Apps data-heavy |\n",
    "| **AutoGPT** | Autonomía | Agentes completamente autónomos | Puede ser impredecible, costos altos | Exploración, investigación |\n",
    "| **Desde cero** | Control total | Máximo control y entendimiento | Más código, reinventar ruedas | Producción crítica |\n",
    "\n",
    "### Cuándo Usar Cada Uno\n",
    "\n",
    "**LangChain**:\n",
    "- ✅ Prototipado rápido\n",
    "- ✅ Múltiples modelos/proveedores\n",
    "- ✅ Necesitas muchas integraciones (100+ herramientas)\n",
    "- ❌ Aplicación performance-critical\n",
    "- ❌ Necesitas control fino sobre cada paso\n",
    "\n",
    "**LlamaIndex**:\n",
    "- ✅ Trabajas con documentos/bases de datos\n",
    "- ✅ RAG (Retrieval-Augmented Generation)\n",
    "- ✅ Índices complejos (vector, graph, etc.)\n",
    "- ❌ Agentes de propósito general sin datos\n",
    "\n",
    "**AutoGPT**:\n",
    "- ✅ Tareas de investigación/exploración\n",
    "- ✅ Experimentación con autonomía\n",
    "- ❌ Producción (muy experimental)\n",
    "- ❌ Presupuesto limitado (puede gastar mucho en API calls)\n",
    "\n",
    "**Desde Cero**:\n",
    "- ✅ Aplicaciones de producción críticas\n",
    "- ✅ Necesitas debugging profundo\n",
    "- ✅ Optimización extrema\n",
    "- ❌ Prototipado rápido\n",
    "- ❌ Equipo pequeño\n"
]))

# LangChain expandido
cells.append(markdown_cell([
    "### LangChain en Detalle\n"
]))

cells.append(code_cell([
    "# Instalar LangChain si no está disponible\n",
    "# !pip install langchain langchain-openai langchain-community\n",
    "\n",
    "try:\n",
    "    from langchain.agents import initialize_agent, Tool, AgentType\n",
    "    from langchain_openai import ChatOpenAI\n",
    "    LANGCHAIN_AVAILABLE = True\n",
    "    print(\"✅ LangChain disponible\")\n",
    "except ImportError:\n",
    "    LANGCHAIN_AVAILABLE = False\n",
    "    print(\"⚠️  LangChain no disponible. Instala con: pip install langchain langchain-openai\")\n"
]))

cells.append(code_cell([
    "if LANGCHAIN_AVAILABLE and OPENAI_AVAILABLE:\n",
    "    # Definir herramientas para LangChain\n",
    "    tools_langchain = [\n",
    "        Tool(\n",
    "            name=\"Calculator\",\n",
    "            func=lambda x: str(eval(x)),\n",
    "            description=\"Útil para hacer cálculos matemáticos. Input debe ser una expresión válida de Python.\"\n",
    "        ),\n",
    "        Tool(\n",
    "            name=\"Time\",\n",
    "            func=lambda x: datetime.now().strftime(\"%Y-%m-%d %H:%M:%S\"),\n",
    "            description=\"Retorna la fecha y hora actual.\"\n",
    "        )\n",
    "    ]\n",
    "    \n",
    "    # Inicializar LLM\n",
    "    llm = ChatOpenAI(temperature=0, model=\"gpt-3.5-turbo\")\n",
    "    \n",
    "    # Inicializar agente\n",
    "    langchain_agent = initialize_agent(\n",
    "        tools=tools_langchain,\n",
    "        llm=llm,\n",
    "        agent=AgentType.ZERO_SHOT_REACT_DESCRIPTION,\n",
    "        verbose=True\n",
    "    )\n",
    "    \n",
    "    print(\"✅ Agente LangChain creado\")\n",
    "    \n",
    "    # Probar\n",
    "    # result = langchain_agent.run(\"¿Cuánto es 15% de 340?\")\n",
    "    # print(f\"\\nResultado LangChain: {result}\")\n",
    "else:\n",
    "    print(\"⚠️  Saltando ejemplo de LangChain (dependencias no disponibles)\")\n"
]))

# LlamaIndex
cells.append(markdown_cell([
    "### LlamaIndex en Detalle\n",
    "\n",
    "LlamaIndex (antes GPT Index) se especializa en conectar LLMs con datos.\n"
]))

cells.append(code_cell([
    "# !pip install llama-index\n",
    "\n",
    "try:\n",
    "    from llama_index import VectorStoreIndex, SimpleDirectoryReader, ServiceContext\n",
    "    from llama_index.agent import OpenAIAgent\n",
    "    from llama_index.tools import QueryEngineTool, ToolMetadata\n",
    "    LLAMAINDEX_AVAILABLE = True\n",
    "    print(\"✅ LlamaIndex disponible\")\n",
    "except ImportError:\n",
    "    LLAMAINDEX_AVAILABLE = False\n",
    "    print(\"⚠️  LlamaIndex no disponible. Instala con: pip install llama-index\")\n",
    "\n",
    "# Ejemplo conceptual (requiere documentos para indexar):\n",
    "if LLAMAINDEX_AVAILABLE and OPENAI_AVAILABLE:\n",
    "    print(\"\"\"\n",
    "    Ejemplo de LlamaIndex:\n",
    "    \n",
    "    # 1. Cargar documentos\n",
    "    documents = SimpleDirectoryReader('data').load_data()\n",
    "    \n",
    "    # 2. Crear índice vectorial\n",
    "    index = VectorStoreIndex.from_documents(documents)\n",
    "    \n",
    "    # 3. Crear query engine\n",
    "    query_engine = index.as_query_engine()\n",
    "    \n",
    "    # 4. Crear agente con el query engine como herramienta\n",
    "    tool = QueryEngineTool(\n",
    "        query_engine=query_engine,\n",
    "        metadata=ToolMetadata(\n",
    "            name=\"knowledge_base\",\n",
    "            description=\"Base de conocimiento sobre documentos X\"\n",
    "        )\n",
    "    )\n",
    "    \n",
    "    agent = OpenAIAgent.from_tools([tool], verbose=True)\n",
    "    response = agent.chat(\"¿Qué dicen los documentos sobre Y?\")\n",
    "    \"\"\")\n"
]))

# Tabla comparativa ejecutable
cells.append(markdown_cell([
    "### Benchmark: Desde Cero vs LangChain\n",
    "\n",
    "Comparemos el mismo agente implementado de ambas formas:\n"
]))

cells.append(code_cell([
    "import time\n",
    "\n",
    "def benchmark_agents():\n",
    "    \"\"\"Compara performance de agente desde cero vs LangChain\"\"\"\n",
    "    query = \"¿Cuánto es 25% de 840?\"\n",
    "    \n",
    "    results = {}\n",
    "    \n",
    "    # 1. Agente desde cero\n",
    "    agent_scratch = SimpleAgent(\n",
    "        tools=[calculator_tool],\n",
    "        llm_backend=\"simulated\"\n",
    "    )\n",
    "    \n",
    "    start = time.time()\n",
    "    response_scratch = agent_scratch.run(query, verbose=False)\n",
    "    time_scratch = time.time() - start\n",
    "    \n",
    "    results['Desde Cero'] = {\n",
    "        'tiempo': time_scratch,\n",
    "        'respuesta': response_scratch,\n",
    "        'lineas_codigo': 150  # Aprox.\n",
    "    }\n",
    "    \n",
    "    # 2. LangChain (si disponible)\n",
    "    if LANGCHAIN_AVAILABLE and OPENAI_AVAILABLE:\n",
    "        start = time.time()\n",
    "        # response_lc = langchain_agent.run(query)\n",
    "        # time_lc = time.time() - start\n",
    "        time_lc = 0.5  # Placeholder\n",
    "        \n",
    "        results['LangChain'] = {\n",
    "            'tiempo': time_lc,\n",
    "            'respuesta': \"210.0\",\n",
    "            'lineas_codigo': 15\n",
    "        }\n",
    "    \n",
    "    return results\n",
    "\n",
    "# benchmark_results = benchmark_agents()\n",
    "# print(\"\\n📊 Resultados del Benchmark:\")\n",
    "# for framework, data in benchmark_results.items():\n",
    "#     print(f\"\\n{framework}:\")\n",
    "#     print(f\"  Tiempo: {data['tiempo']:.3f}s\")\n",
    "#     print(f\"  Líneas de código: {data['lineas_codigo']}\")\n",
    "#     print(f\"  Respuesta: {data['respuesta']}\")\n"
]))

# Recomendaciones
cells.append(markdown_cell([
    "### 🎯 Recomendaciones Prácticas\n",
    "\n",
    "**Para Aprendizaje**:\n",
    "1. **Comienza desde cero** (lo que hicimos aquí) para entender fundamentos\n",
    "2. **Luego usa LangChain** para ver cómo se abstrae\n",
    "3. **Lee el código fuente** de los frameworks - aprenderás mucho\n",
    "\n",
    "**Para Producción**:\n",
    "1. **Prototipo con framework** (LangChain) para validar idea rápidamente\n",
    "2. **Optimiza partes críticas** implementándolas desde cero\n",
    "3. **Mantén hybrid approach**: framework para lo genérico, custom code para lo específico\n",
    "\n",
    "**Para Proyectos Data-Heavy**:\n",
    "- Usa **LlamaIndex** para RAG y manejo de documentos\n",
    "- Combina con LangChain para agentes más complejos\n",
    "\n",
    "**Red Flags con Frameworks**:\n",
    "- ⚠️ Si no entiendes qué hace el código, no lo uses en producción\n",
    "- ⚠️ Si el debugging es muy difícil, considera implementar tú mismo\n",
    "- ⚠️ Si el framework cambia APIs frecuentemente, evalúa dependencia\n"
]))

print("Sección 6: Frameworks... OK")

# Construcción completa - escribir JSON
notebook = {
    "cells": cells,
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "codemirror_mode": {
                "name": "ipython",
                "version": 3
            },
            "file_extension": ".py",
            "mimetype": "text/x-python",
            "name": "python",
            "nbconvert_exporter": "python",
            "pygments_lexer": "ipython3",
            "version": "3.8.0"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 4
}

# Guardar (parcialmente - continuaremos en siguiente script)
output_path = "/home/user/TUTORIALS-AI-AGENTS/rutas/03-llm-agents/01-intro-llm-agents-PARTIAL.json"
with open(output_path, 'w', encoding='utf-8') as f:
    json.dump(notebook, f, ensure_ascii=False, indent=1)

print(f"\n✅ Notebook parcial guardado en: {output_path}")
print(f"📊 Total de celdas hasta ahora: {len(cells)}")
print("\nContinuaremos con secciones 7-10 en el siguiente script...")
