#!/usr/bin/env python3
"""Script para refactorizar notebook 06-multi-agentes.ipynb"""

import json

def md(lines):
    """Crea celda markdown"""
    return {
        "cell_type": "markdown",
        "metadata": {},
        "source": lines
    }

def code(lines):
    """Crea celda de código"""
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": lines
    }

# Cargar original
with open('06-multi-agentes-ORIGINAL-BACKUP.ipynb', 'r') as f:
    original = json.load(f)

orig_cells = original['cells']

# Construir notebook refactorizado
cells = []

# ========== HEADER CON TOC ==========
cells.append(md([
    "# 06. Sistemas Multi-Agente\n",
    "\n",
    "**Nivel:** 🔴 Avanzado  \n",
    "**Tiempo estimado:** 120 minutos  \n",
    "**Prerequisitos:** [01-05: Todos los notebooks anteriores](01-intro-llm-agents.ipynb)\n",
    "\n",
    "## 📋 Tabla de Contenidos\n",
    "\n",
    "1. [Motivación: ¿Por Qué Multi-Agente?](#1-motivacion)\n",
    "2. [Patrones de Multi-Agente](#2-patrones)\n",
    "3. [Implementación: Base Agent Framework](#3-implementacion)\n",
    "4. [Patrón Sequential](#4-sequential)\n",
    "5. [**🎯 Ejercicios GRADED**](#5-ejercicios-graded) ⭐\n",
    "6. [Papers Fundamentales](#6-papers)\n",
    "7. [Best Practices](#7-best-practices)\n",
    "8. [Conclusiones](#8-conclusiones)\n",
    "9. [Referencias](#9-referencias)\n",
    "10. [Navegación](#10-navegacion)\n",
    "\n",
    "---\n",
    "\n",
    "## 🎯 Objetivos de Aprendizaje\n",
    "\n",
    "Al finalizar este notebook, podrás:\n",
    "- Diseñar sistemas con múltiples agentes especializados\n",
    "- Implementar patrones de colaboración entre agentes\n",
    "- Construir sistemas AutoGPT-style con task decomposition\n",
    "- Entender BabyAGI y arquitecturas de planificación\n",
    "- Manejar comunicación y coordinación multi-agente\n",
    "- Aplicar patrones: Sequential, Hierarchical, Debate, Autonomous\n"
]))

# ========== SECCIONES 1-4: CONTENIDO ORIGINAL ==========
# Copiar celdas 1-12 del original (motivación, patrones, implementación, sequential, hierarchical, autogpt)
cells.extend(orig_cells[1:13])

# ========== SECCIÓN 5: EJERCICIOS GRADED ==========
cells.append(md([
    "## 5. 🎯 Ejercicios GRADED\n",
    "\n",
    "**IMPORTANTE:** Esta sección contiene los ejercicios evaluados del notebook.\n",
    "\n",
    "- **Total de puntos:** 100\n",
    "- **Puntos para aprobar:** 70\n",
    "- **Ejercicios:** 5\n",
    "\n",
    "### 📝 Instrucciones\n",
    "\n",
    "1. Completa cada función marcada con `# TODO`\n",
    "2. Ejecuta las pruebas con: `pytest tests/test_06_multi_agentes.py -v`\n",
    "3. Verifica tu puntuación total\n",
    "\n",
    "---\n"
]))

# Ejercicio 1: implement_sequential_pipeline (20 pts)
cells.append(md([
    "### Ejercicio 1: Implementar Sequential Pipeline (20 puntos)\n",
    "\n",
    "**Objetivo:** Crear pipeline secuencial donde output de un agente es input del siguiente.\n",
    "\n",
    "**Requisitos:**\n",
    "- Ejecutar agentes en orden definido\n",
    "- Pasar output de agente N como input a agente N+1\n",
    "- Retornar resultado final del último agente\n",
    "- Manejar pipeline vacío correctamente\n",
    "\n",
    "**Tests validarán:**\n",
    "- Pipeline ejecuta todos los agentes en orden\n",
    "- Transformaciones se aplican secuencialmente\n",
    "- Edge cases (pipeline vacío, single agent)\n",
    "- Resultado final correcto\n"
]))

cells.append(code([
    "def implement_sequential_pipeline(agents: List, initial_input: str) -> str:\n",
    "    \"\"\"\n",
    "    Implementa pipeline secuencial de agentes.\n",
    "    \n",
    "    Args:\n",
    "        agents: Lista de funciones/agentes que procesan datos\n",
    "        initial_input: Input inicial para el primer agente\n",
    "    \n",
    "    Returns:\n",
    "        Output final del último agente en el pipeline\n",
    "    \n",
    "    Ejemplo:\n",
    "        >>> def agent1(x): return x.upper()\n",
    "        >>> def agent2(x): return f\"PREFIX-{x}\"\n",
    "        >>> def agent3(x): return f\"{x}-SUFFIX\"\n",
    "        >>> implement_sequential_pipeline([agent1, agent2, agent3], \"hello\")\n",
    "        \"PREFIX-HELLO-SUFFIX\"\n",
    "    \"\"\"\n",
    "    # TODO: Implementar aquí\n",
    "    # Pista: Iterar sobre agents, pasar output de uno como input del siguiente\n",
    "    pass\n"
]))

# Ejercicio 2: task_decomposition (20 pts)
cells.append(md([
    "### Ejercicio 2: Descomposición de Tareas (20 puntos)\n",
    "\n",
    "**Objetivo:** Descomponer tareas complejas en subtareas atómicas.\n",
    "\n",
    "**Requisitos:**\n",
    "- Analizar tarea compleja\n",
    "- Generar lista de subtareas accionables\n",
    "- Subtareas deben ser independientes o con dependencias claras\n",
    "- Evitar sobre-descomposición de tareas simples\n",
    "\n",
    "**Tests validarán:**\n",
    "- Tarea compleja genera múltiples subtareas\n",
    "- Subtareas tienen estructura clara\n",
    "- Tarea simple no se sobre-descompone\n",
    "- Consistencia en múltiples descomposiciones\n"
]))

cells.append(code([
    "def task_decomposition(task: str, include_metadata: bool = False) -> List:\n",
    "    \"\"\"\n",
    "    Descompone tarea en subtareas atómicas.\n",
    "    \n",
    "    Args:\n",
    "        task: Descripción de la tarea compleja\n",
    "        include_metadata: Si True, retorna dicts con metadata\n",
    "    \n",
    "    Returns:\n",
    "        Lista de subtareas (strings o dicts)\n",
    "    \n",
    "    Ejemplo:\n",
    "        >>> task_decomposition(\"Crear aplicación web\", include_metadata=False)\n",
    "        [\n",
    "            \"Diseñar arquitectura\",\n",
    "            \"Implementar backend\",\n",
    "            \"Crear frontend\",\n",
    "            \"Escribir tests\",\n",
    "            \"Documentar API\"\n",
    "        ]\n",
    "        \n",
    "        >>> task_decomposition(\"Crear app\", include_metadata=True)\n",
    "        [\n",
    "            {\"task\": \"Diseñar arquitectura\", \"priority\": \"high\"},\n",
    "            {\"task\": \"Implementar backend\", \"priority\": \"medium\"},\n",
    "            ...\n",
    "        ]\n",
    "    \"\"\"\n",
    "    # TODO: Implementar aquí\n",
    "    # Pista: Identificar keywords (web, API, app) y generar subtareas relevantes\n",
    "    pass\n"
]))

# Ejercicio 3: agent_communication (25 pts)
cells.append(md([
    "### Ejercicio 3: Sistema de Comunicación entre Agentes (25 puntos)\n",
    "\n",
    "**Objetivo:** Implementar sistema de mensaje passing entre agentes.\n",
    "\n",
    "**Requisitos:**\n",
    "- Agentes pueden enviar mensajes a otros agentes\n",
    "- Agentes pueden recibir mensajes dirigidos a ellos\n",
    "- Sistema de routing entrega mensajes correctamente\n",
    "- Soporte para broadcast (mensaje a todos)\n",
    "\n",
    "**Tests validarán:**\n",
    "- Envío de mensajes exitoso\n",
    "- Recepción de mensajes correcta\n",
    "- Filtrado por destinatario\n",
    "- Broadcast a múltiples agentes\n"
]))

cells.append(code([
    "def agent_communication():\n",
    "    \"\"\"\n",
    "    Crea sistema de comunicación entre agentes.\n",
    "    \n",
    "    Returns:\n",
    "        Objeto con métodos:\n",
    "        - send(message): Enviar mensaje\n",
    "        - receive(agent_id): Recibir mensajes para un agente\n",
    "    \n",
    "    Ejemplo:\n",
    "        >>> comm = agent_communication()\n",
    "        >>> comm.send({\"from\": \"agent1\", \"to\": \"agent2\", \"content\": \"Hello\"})\n",
    "        True\n",
    "        >>> comm.receive(\"agent2\")\n",
    "        [{\"from\": \"agent1\", \"to\": \"agent2\", \"content\": \"Hello\"}]\n",
    "        \n",
    "        # Broadcast\n",
    "        >>> comm.send({\"from\": \"manager\", \"to\": \"all\", \"content\": \"Important!\"})\n",
    "        >>> comm.receive(\"agent1\")  # Todos reciben\n",
    "        [{\"from\": \"manager\", \"to\": \"all\", \"content\": \"Important!\"}]\n",
    "    \"\"\"\n",
    "    # TODO: Implementar aquí\n",
    "    # Pista: Usar message queue (list) y filtrar por destinatario\n",
    "    pass\n"
]))

# Ejercicio 4: consensus_mechanism (20 pts)
cells.append(md([
    "### Ejercicio 4: Mecanismo de Consenso (20 puntos)\n",
    "\n",
    "**Objetivo:** Implementar sistema de voting/consenso entre agentes.\n",
    "\n",
    "**Requisitos:**\n",
    "- Múltiples agentes proponen soluciones\n",
    "- Sistema de voting determina ganador\n",
    "- Soporte para diferentes modos (voting, scoring)\n",
    "- Manejo de empates\n",
    "\n",
    "**Tests validarán:**\n",
    "- Voting simple funciona\n",
    "- Empates se manejan razonablemente\n",
    "- Ranking por scores correcto\n",
    "- Consenso multi-ronda\n"
]))

cells.append(code([
    "def consensus_mechanism(proposals: List[str], votes_or_scores: Dict, mode: str = \"votes\") -> str:\n",
    "    \"\"\"\n",
    "    Determina consenso entre múltiples propuestas.\n",
    "    \n",
    "    Args:\n",
    "        proposals: Lista de propuestas\n",
    "        votes_or_scores: Dict con votos o scores\n",
    "        mode: \"votes\" para voting, \"scores\" para ranking\n",
    "    \n",
    "    Returns:\n",
    "        Propuesta ganadora\n",
    "    \n",
    "    Ejemplo (voting):\n",
    "        >>> proposals = [\"option_a\", \"option_b\", \"option_c\"]\n",
    "        >>> votes = {\n",
    "        ...     \"agent1\": \"option_a\",\n",
    "        ...     \"agent2\": \"option_a\",\n",
    "        ...     \"agent3\": \"option_b\"\n",
    "        ... }\n",
    "        >>> consensus_mechanism(proposals, votes)\n",
    "        \"option_a\"\n",
    "    \n",
    "    Ejemplo (scores):\n",
    "        >>> proposals = [\"p1\", \"p2\", \"p3\"]\n",
    "        >>> scores = {\"p1\": 7.5, \"p2\": 9.2, \"p3\": 8.1}\n",
    "        >>> consensus_mechanism(proposals, scores, mode=\"scores\")\n",
    "        \"p2\"\n",
    "    \"\"\"\n",
    "    # TODO: Implementar aquí\n",
    "    # Pista: Contar votos o encontrar max score\n",
    "    pass\n"
]))

# Ejercicio 5: autonomous_loop (15 pts)
cells.append(md([
    "### Ejercicio 5: Loop Autónomo (AutoGPT) (15 puntos)\n",
    "\n",
    "**Objetivo:** Implementar loop autónomo estilo AutoGPT.\n",
    "\n",
    "**Requisitos:**\n",
    "- Ejecutar iteraciones hasta alcanzar objetivo\n",
    "- Criterio de terminación flexible\n",
    "- Max iterations para prevenir loops infinitos\n",
    "- Estado persistente entre iteraciones\n",
    "\n",
    "**Tests validarán:**\n",
    "- Loop ejecuta correctamente\n",
    "- Terminación por criterio funciona\n",
    "- Max iterations se respeta\n",
    "- Estado se mantiene entre iteraciones\n"
]))

cells.append(code([
    "def autonomous_loop(goal: str, max_iterations: int = 10, \n",
    "                   termination_fn=None, track_state: bool = False) -> Dict:\n",
    "    \"\"\"\n",
    "    Implementa loop autónomo estilo AutoGPT.\n",
    "    \n",
    "    Args:\n",
    "        goal: Objetivo a alcanzar\n",
    "        max_iterations: Máximo de iteraciones\n",
    "        termination_fn: Función que determina cuándo terminar\n",
    "        track_state: Si True, mantiene estado entre iteraciones\n",
    "    \n",
    "    Returns:\n",
    "        Dict con resultado y metadata del loop\n",
    "    \n",
    "    Ejemplo:\n",
    "        >>> def check_done(iteration, state):\n",
    "        ...     return iteration >= 3\n",
    "        >>> result = autonomous_loop(\n",
    "        ...     \"solve problem\",\n",
    "        ...     max_iterations=10,\n",
    "        ...     termination_fn=check_done\n",
    "        ... )\n",
    "        >>> result['iterations']\n",
    "        3\n",
    "    \"\"\"\n",
    "    # TODO: Implementar aquí\n",
    "    # Pista: Loop while i < max_iterations, checkear termination_fn\n",
    "    pass\n"
]))

# ========== SECCIÓN 6: PAPERS ==========
cells.append(md([
    "## 6. 📄 Papers Fundamentales\n",
    "\n",
    "### Paper 1: AutoGPT - Autonomous GPT-4\n",
    "\n",
    "**\"AutoGPT: An Autonomous GPT-4 Experiment\"**  \n",
    "*Significant Gravitas, 2023*  \n",
    "[GitHub](https://github.com/Significant-Gravitas/AutoGPT)\n",
    "\n",
    "**Contribución clave:**\n",
    "- Agente autónomo que ejecuta loops Think-Plan-Execute\n",
    "- Acceso a herramientas: web browsing, code execution, file I/O\n",
    "- Self-prompting: genera sus propios prompts para subtareas\n",
    "\n",
    "**Arquitectura:**\n",
    "```\n",
    "Goal\n",
    " ↓\n",
    "While not achieved:\n",
    "  1. Think: Analyze current state\n",
    "  2. Plan: Decide next action\n",
    "  3. Execute: Use tools\n",
    "  4. Evaluate: Check progress\n",
    "```\n",
    "\n",
    "**Impacto:** Inspiró frameworks de agentes autónomos (BabyAGI, AgentGPT, etc.)\n",
    "\n",
    "---\n",
    "\n",
    "### Paper 2: BabyAGI - Task-Driven Autonomous Agent\n",
    "\n",
    "**\"BabyAGI: Task-driven Autonomous Agent\"**  \n",
    "*Yohei Nakajima, 2023*  \n",
    "[GitHub](https://github.com/yoheinakajima/babyagi)\n",
    "\n",
    "**Contribución clave:**\n",
    "- Sistema de 3 agentes especializados:\n",
    "  - **Execution Agent**: Ejecuta tareas\n",
    "  - **Task Creation Agent**: Genera nuevas tareas\n",
    "  - **Prioritization Agent**: Reordena task queue\n",
    "- Usa vector memory (Pinecone) para contexto\n",
    "\n",
    "**Loop principal:**\n",
    "```python\n",
    "while task_queue:\n",
    "    task = task_queue.pop(0)  # Highest priority\n",
    "    result = execution_agent(task)\n",
    "    new_tasks = task_creation_agent(result)\n",
    "    task_queue = prioritization_agent(task_queue + new_tasks)\n",
    "```\n",
    "\n",
    "**Impacto:** Demostró viabilidad de agentes task-driven en <300 líneas de código\n",
    "\n",
    "---\n",
    "\n",
    "### Paper 3: ChatDev - Communicative Agents for Software Development\n",
    "\n",
    "**\"Communicative Agents for Software Development\"**  \n",
    "*Qian et al., Tsinghua University, 2023*  \n",
    "[arXiv:2307.07924](https://arxiv.org/abs/2307.07924) | [GitHub](https://github.com/OpenBMB/ChatDev)\n",
    "\n",
    "**Contribución clave:**\n",
    "- Sistema multi-agente para desarrollo completo de software\n",
    "- Agentes con roles especializados: CEO, CTO, Programmer, Tester, Designer\n",
    "- Fases de desarrollo: Design → Coding → Testing → Documentation\n",
    "\n",
    "**Arquitectura:**\n",
    "```\n",
    "CEO (Manager)\n",
    " ↓\n",
    "CTO → Programmer → Code Reviewer → Tester → Designer\n",
    "```\n",
    "\n",
    "**Resultados:**\n",
    "- Genera software funcional end-to-end (promedio 7 min)\n",
    "- Código con menos bugs que baseline single-agent\n",
    "- Costo: ~$0.20 por proyecto simple\n",
    "\n",
    "---\n",
    "\n",
    "### Paper 4: MetaGPT - Multi-Agent Framework\n",
    "\n",
    "**\"MetaGPT: Meta Programming for Multi-Agent Collaborative Framework\"**  \n",
    "*Hong et al., 2023*  \n",
    "[arXiv:2308.00352](https://arxiv.org/abs/2308.00352)\n",
    "\n",
    "**Contribución clave:**\n",
    "- Standardized Operating Procedures (SOPs) para coordinación\n",
    "- Agentes comparten \"workspace\" estructurado\n",
    "- Generación incremental con human-in-the-loop\n",
    "\n",
    "**Key insight:**\n",
    "> \"Human collaboration works because of shared context and structured workflows.\"\n",
    "> \"Multi-agent systems should mimic this.\"\n",
    "\n",
    "**Impacto:** Framework usado en producción para code generation\n"
]))

# ========== SECCIÓN 7: BEST PRACTICES ==========
cells.append(md([
    "## 7. ✅ Best Practices\n",
    "\n",
    "### 1. Diseño de Sistemas Multi-Agente\n",
    "\n",
    "**✅ DO:**\n",
    "- Definir roles claros para cada agente\n",
    "- Un agente, una responsabilidad (Single Responsibility Principle)\n",
    "- Usar manager/coordinator para orquestación\n",
    "- Implementar comunicación explícita (message passing)\n",
    "\n",
    "**❌ DON'T:**\n",
    "- Crear agentes con roles superpuestos\n",
    "- Comunicación implícita (shared state sin sincronización)\n",
    "- Over-engineering: más agentes ≠ mejor sistema\n",
    "\n",
    "---\n",
    "\n",
    "### 2. Patrones de Colaboración\n",
    "\n",
    "**Cuándo usar cada patrón:**\n",
    "\n",
    "| Patrón | Caso de Uso | Ejemplo |\n",
    "|--------|-------------|----------|\n",
    "| **Sequential** | Pipeline lineal | Research → Write → Review |\n",
    "| **Hierarchical** | Tareas complejas | Manager delega a specialists |\n",
    "| **Debate** | Decisiones críticas | 3 agentes proponen, votan |\n",
    "| **AutoGPT** | Objetivo abierto | \"Crear startup exitosa\" |\n",
    "\n",
    "---\n",
    "\n",
    "### 3. Comunicación entre Agentes\n",
    "\n",
    "**Diseño de mensajes:**\n",
    "\n",
    "```python\n",
    "# ✅ GOOD: Mensaje estructurado\n",
    "message = {\n",
    "    \"from\": \"agent_id\",\n",
    "    \"to\": \"recipient_id\",\n",
    "    \"type\": \"request\" | \"response\" | \"notification\",\n",
    "    \"content\": {...},\n",
    "    \"metadata\": {\n",
    "        \"timestamp\": \"2024-01-15T10:30:00Z\",\n",
    "        \"priority\": \"high\",\n",
    "        \"conversation_id\": \"conv_123\"\n",
    "    }\n",
    "}\n",
    "\n",
    "# ❌ BAD: String ambiguo\n",
    "message = \"Hey agent2, do something with this data: ...\"\n",
    "```\n",
    "\n",
    "---\n",
    "\n",
    "### 4. Prevención de Loops Infinitos\n",
    "\n",
    "**Estrategias críticas:**\n",
    "\n",
    "```python\n",
    "# 1. Max iterations SIEMPRE\n",
    "MAX_ITERATIONS = 50\n",
    "\n",
    "# 2. Timeout global\n",
    "import signal\n",
    "signal.alarm(300)  # 5 min timeout\n",
    "\n",
    "# 3. Progress tracking\n",
    "def check_progress(iteration, prev_state, current_state):\n",
    "    if iteration > 10 and prev_state == current_state:\n",
    "        raise StuckError(\"No progress in 10 iterations\")\n",
    "\n",
    "# 4. Cost limits\n",
    "total_cost = 0\n",
    "MAX_COST = 5.0  # $5 limit\n",
    "if total_cost > MAX_COST:\n",
    "    raise BudgetExceededError()\n",
    "```\n",
    "\n",
    "---\n",
    "\n",
    "### 5. Debugging Multi-Agent Systems\n",
    "\n",
    "**Técnicas efectivas:**\n",
    "\n",
    "```python\n",
    "# 1. Logging estructurado\n",
    "import logging\n",
    "\n",
    "logger.info(\n",
    "    \"Agent action\",\n",
    "    extra={\n",
    "        \"agent_id\": self.id,\n",
    "        \"action\": \"send_message\",\n",
    "        \"to\": recipient,\n",
    "        \"iteration\": current_iteration\n",
    "    }\n",
    ")\n",
    "\n",
    "# 2. Visualización de flujos\n",
    "# Exportar trace a formato gráfico\n",
    "trace.export_to_mermaid()  # Diagrama de secuencia\n",
    "\n",
    "# 3. Unit test de agentes individuales\n",
    "def test_researcher_agent():\n",
    "    agent = ResearcherAgent()\n",
    "    result = agent.process(\"test task\")\n",
    "    assert \"research\" in result.lower()\n",
    "```\n",
    "\n",
    "---\n",
    "\n",
    "### 6. Cost Optimization\n",
    "\n",
    "**Estrategias:**\n",
    "\n",
    "1. **Cache agresivo**: Resultados de agentes idénticos\n",
    "2. **Modelos por rol**: GPT-4 para manager, GPT-3.5 para workers\n",
    "3. **Batch processing**: Agrupar llamadas similares\n",
    "4. **Early stopping**: Detectar éxito temprano\n",
    "\n",
    "```python\n",
    "# Ejemplo: Modelos diferenciados\n",
    "AGENT_MODELS = {\n",
    "    \"manager\": \"gpt-4-turbo\",      # Necesita razonamiento complejo\n",
    "    \"researcher\": \"gpt-4-turbo\",   # Necesita precisión\n",
    "    \"writer\": \"gpt-3.5-turbo\",     # Tarea más simple\n",
    "    \"formatter\": \"gpt-3.5-turbo\"   # Tarea mecánica\n",
    "}\n",
    "```\n",
    "\n",
    "---\n",
    "\n",
    "### 7. Evaluación de Sistemas Multi-Agente\n",
    "\n",
    "**Métricas clave:**\n",
    "\n",
    "```python\n",
    "metrics = {\n",
    "    # Performance\n",
    "    \"task_success_rate\": 0.85,\n",
    "    \"avg_iterations\": 12.3,\n",
    "    \"avg_completion_time_sec\": 45.2,\n",
    "    \n",
    "    # Quality\n",
    "    \"output_quality_score\": 8.5,  # Human eval 1-10\n",
    "    \"error_rate\": 0.05,\n",
    "    \n",
    "    # Cost\n",
    "    \"avg_cost_usd\": 0.42,\n",
    "    \"cost_per_success\": 0.49,\n",
    "    \n",
    "    # Collaboration\n",
    "    \"avg_messages_exchanged\": 8.2,\n",
    "    \"consensus_rounds\": 1.5\n",
    "}\n",
    "```\n"
]))

# ========== SECCIÓN 8: CONCLUSIONES ==========
cells.append(md([
    "## 8. 🎓 Conclusiones\n",
    "\n",
    "### Conceptos Clave\n",
    "\n",
    "1. **Especialización > Generalización**: Agentes especializados superan a generalistas\n",
    "2. **Patrones fundamentales**: Sequential, Hierarchical, Debate, Autonomous\n",
    "3. **Comunicación explícita**: Message passing estructurado\n",
    "4. **Coordinación**: Manager/orchestrator o protocolos de consenso\n",
    "5. **Safety**: Max iterations, timeouts, cost limits\n",
    "\n",
    "### Pregunta Inicial: ¿RESPONDIDA?\n",
    "\n",
    "**Pregunta:** *¿Cómo diseñar sistemas multi-agente efectivos?*\n",
    "\n",
    "**Respuesta:**\n",
    "1. **Definir roles claros** para cada agente (especialización)\n",
    "2. **Elegir patrón adecuado** según tipo de tarea\n",
    "3. **Implementar comunicación estructurada** (message passing)\n",
    "4. **Coordinar con manager** o protocolo de consenso\n",
    "5. **Monitorear y limitar** iteraciones, costos, tiempo\n",
    "\n",
    "### Lo Aprendido\n",
    "\n",
    "- ✅ Patrones de colaboración multi-agente\n",
    "- ✅ Implementación de pipelines y hierarchies\n",
    "- ✅ Sistemas autónomos (AutoGPT, BabyAGI)\n",
    "- ✅ Comunicación y consenso\n",
    "- ✅ Best practices y debugging\n",
    "\n",
    "### El Futuro de Multi-Agent Systems\n",
    "\n",
    "**Tendencias emergentes:**\n",
    "\n",
    "1. **Human-in-the-loop**: Agentes colaboran con humanos\n",
    "2. **Self-improvement**: Agentes que mejoran su código\n",
    "3. **Large-scale coordination**: 100s-1000s de agentes\n",
    "4. **Domain-specific**: Agentes especializados por industria\n",
    "\n",
    "---\n",
    "\n",
    "<div align=\"center\">\n",
    "\n",
    "## 🎉 ¡Felicitaciones!\n",
    "\n",
    "**Has completado la Ruta 3: LLM Agents**\n",
    "\n",
    "Ahora dominas:\n",
    "- Fundamentos de LLM Agents\n",
    "- Prompting agéntico\n",
    "- ReAct pattern\n",
    "- Tool use & function calling\n",
    "- Memory systems\n",
    "- **Sistemas multi-agente**\n",
    "\n",
    "### Próximos pasos:\n",
    "\n",
    "1. **Construye proyectos reales** con agentes\n",
    "2. **Explora frameworks**: LangChain, AutoGPT, CrewAI\n",
    "3. **Lee papers recientes** de agentic AI\n",
    "4. **Contribuye** a proyectos open-source\n",
    "\n",
    "</div>\n"
]))

# ========== SECCIÓN 9: REFERENCIAS ==========
cells.append(md([
    "## 9. 📚 Referencias\n",
    "\n",
    "### Papers\n",
    "\n",
    "1. AutoGPT - [GitHub](https://github.com/Significant-Gravitas/AutoGPT)\n",
    "2. BabyAGI - [GitHub](https://github.com/yoheinakajima/babyagi)\n",
    "3. Qian et al. (2023) - [Communicative Agents (ChatDev)](https://arxiv.org/abs/2307.07924)\n",
    "4. Hong et al. (2023) - [MetaGPT](https://arxiv.org/abs/2308.00352)\n",
    "\n",
    "### Proyectos Open Source\n",
    "\n",
    "- **AutoGPT**: Autonomous GPT-4 agent\n",
    "- **BabyAGI**: Task-driven autonomous agent\n",
    "- **ChatDev**: Communicative agents for software dev\n",
    "- **MetaGPT**: Multi-agent meta programming\n",
    "- **CrewAI**: Framework for orchestrating role-playing AI agents\n",
    "- **AgentGPT**: Browser-based autonomous AI agents\n",
    "\n",
    "### Frameworks\n",
    "\n",
    "- [LangChain Multi-Agent](https://python.langchain.com/docs/modules/agents/)\n",
    "- [CrewAI](https://github.com/joaomdmoura/crewAI)\n",
    "- [AutoGen (Microsoft)](https://github.com/microsoft/autogen)\n",
    "\n",
    "### Documentación\n",
    "\n",
    "- [OpenAI Function Calling](https://platform.openai.com/docs/guides/function-calling)\n",
    "- [Anthropic Claude Agents](https://docs.anthropic.com/claude/docs)\n"
]))

# ========== SECCIÓN 10: NAVEGACIÓN ==========
cells.append(md([
    "## 10. 🧭 Navegación\n",
    "\n",
    "### Notebooks de la Ruta LLM Agents\n",
    "\n",
    "1. [01 - Introducción a LLM Agents](01-intro-llm-agents.ipynb)\n",
    "2. [02 - Prompting Agéntico](02-prompting-agentico.ipynb)\n",
    "3. [03 - ReAct (Reasoning + Acting)](03-react-reasoning-acting.ipynb)\n",
    "4. [04 - Tool Use & Function Calling](04-tool-use-function-calling.ipynb)\n",
    "5. [05 - Memory Systems](05-memory-systems.ipynb)\n",
    "6. **[06 - Sistemas Multi-Agente](06-multi-agentes.ipynb)** ⭐ Estás aquí\n",
    "\n",
    "---\n",
    "\n",
    "### ⬅️ Anterior\n",
    "\n",
    "**[⬅️ 05 - Memory Systems](05-memory-systems.ipynb)**\n",
    "\n",
    "---\n",
    "\n",
    "<div align=\"center\">\n",
    "\n",
    "## 🎊 ¡Ruta Completada!\n",
    "\n",
    "**Has terminado todos los notebooks de LLM Agents.**\n",
    "\n",
    "**[🏠 Volver al índice principal](../../README.md)**\n",
    "\n",
    "---\n",
    "\n",
    "*Construye el futuro con AI Agents* 🚀\n",
    "\n",
    "</div>\n"
]))

# ========== CONSTRUIR NOTEBOOK FINAL ==========
refactored = {
    "cells": cells,
    "metadata": original["metadata"],
    "nbformat": original["nbformat"],
    "nbformat_minor": original["nbformat_minor"]
}

# Guardar
with open('06-multi-agentes.ipynb', 'w', encoding='utf-8') as f:
    json.dump(refactored, f, ensure_ascii=False, indent=1)

print(f"✅ Notebook refactorizado: {len(cells)} celdas")
print("📊 Estructura:")
print("  - Header con TOC")
print("  - Secciones 1-4: Contenido original")
print("  - Sección 5: 5 ejercicios GRADED (100 pts)")
print("  - Sección 6: 4 papers fundamentales")
print("  - Sección 7: Best practices completas")
print("  - Secciones 8-10: Conclusiones, referencias, navegación")
